- name: 创建临时目录
  file: dest={{tmp_dir}} state=directory

- name: 创建token
  shell: "kubeadm token create --print-join-command > {{ tmp_dir }}/join-token.txt 2>&1"

- name: 创建node脚本
  shell: "grep -A1 'kubeadm join' {{ tmp_dir }}/join-token.txt > {{ tmp_dir }}/node-join.sh"

- name: 
  shell: cat {{ tmp_dir }}/node-join.sh
  register: addinfo
- set_fact: add_node={{addinfo.stdout}}

- name: 本地获取node脚本
  local_action: shell {{ item }}
  with_items:
  - "mkdir -p {{tmp_dir}}"
  - "echo {{add_node}} >> {{ tmp_dir }}/node-join.sh"

- name: 添加新节点
  shell: "{{ item }}"
  connection: local
  args:
    warn: False
  with_items:
  - "ansible add_node -i /home/k8s/hosts -m file -a 'dest={{ tmp_dir }} state=directory'"
  - "ansible add_node -i /home/k8s/hosts -m template -a 'src={{ tmp_dir }}/node-join.sh dest={{ tmp_dir }}'"
  - "ansible add_node -i /home/k8s/hosts -m shell -a 'swapoff -a && kubeadm reset -f'"
  - "ansible add_node -i /home/k8s/hosts -m shell -a 'sh {{ tmp_dir }}/node-join.sh'"

#- name: node节点添加临时存放目录
#  shell: "ansible add_node -m file -a 'dest={{ tmp_dir }} state=directory'"
  
#- name: 分发node-join.sh
#  shell: "ansible add_node -m template -a 'src={{ tmp_dir }}/node-join.sh dest={{ tmp_dir }}'"
  


